class AnnouncementPageLocators:
    hyperlink_announcement_xpath = "//a[normalize-space()='Announcements']"
    button_new_announcement_xpath = "//button[normalize-space()='New Announcement']"
    input_announcement_name_xpath = "//input[@id='announcement-name']"
    textarea_description_xpath = "//textarea[@id='description']"
    option_type_image_xpath = "(//option[@value='Image'][normalize-space()='Image'])[2]"
    option_redirect_store_xpath = "//option[@value='STORE']"
    button_save_xpath = "//*[@id='announcementModal']/div[1]/div/form/div[3]/div/button[3]"
    button_schedule_xpath = "//button[@id='announce-schedule-btn']"
    td_start_date_xpath = "//*[@id='announcementModal']/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[2]"
    td_end_date_xpath = "//*[@id='announcementModal']/div[2]/div[2]/div[2]/table/tbody/tr[3]/td[5]"
    button_apply_xpath = "//button[normalize-space()='Apply']"
    option_start_time_hour_xpath = "(//option[@value='4'][normalize-space()='4'])[1]"
    option_start_time_minute_xpath = "(//option[@value='30'][normalize-space()='30'])[1]"
    option_end_time_hour_xpath = "(//option[@value='10'][normalize-space()='10'])[3]"
    option_end_time_minute_xpath = "(//option[@value='20'][normalize-space()='20'])[2]"
    option_start_am_xpath = "(//option[@value='AM'][normalize-space()='AM'])[1]"
    option_end_pm_xpath = "(//option[@value='PM'][normalize-space()='PM'])[2]"
    hyperlink_page_xpath = "(//a[normalize-space()='4'])[1]"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[12]"
    button_delete_xpath = "(//button[@data-bs-target='#delete-announcement-model'])[1]"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    input_search_announcement_xpath = "//input[@name='search-name']"
    option_active_status_all_xpath = "(//option[contains(text(),'All')])[1]"
    option_active_status_active_xpath = "//option[@value='true']"
    option_active_status_inactive_xpath = "//option[@value='false']"
    option_type_all_xpath = "(//option[contains(text(),'All')])[2]"
    option_type_text_xpath = "(//option[@value='Text'][normalize-space()='Text'])[1]"
    option_type_search_image_xpath = "(//option[@value='Image'][normalize-space()='Image'])[1]"
    input_start_date_xpath = "//input[@placeholder='Start Date']"
    input_end_date_xpath = "//input[@placeholder='End Date']"
    button_search_xpath = "(//button[@type='submit'])[2]"
    button_refresh_xpath = "//i[@class='fas fa-refresh']"
    button_choose_image_xpath = "//button[normalize-space()='Choose new image']"
    button_advanced_filter_xpath = "//button[normalize-space()='Advanced Filters']"
    hyperlink_page22_xpath = "(//a[normalize-space()='22'])[1]"
    image_path = "C:\\Users\\Ishadi\\Documents\\GitHub\\playpointz-test-automation\\Images\\test_image_announcement.jpg"
