class CampaignsLocators:
    hyperlink_campaigns_xpath = "//a[normalize-space()='Campaigns']"
    button_create_campaign_xpath = "//button[normalize-space()='New Campaign']"
    input_campaign_name_xpath = "//input[@id='campaign-name']"
    input_headline_xpath = "//input[@id='campaign-headline']"
    input_sponsor_xpath = "//input[@id='sponsor']"
    option_placement_xpath = "//option[@value='Feed']"
    option_campaign_type_xpath = "//option[@value='Image']"
    option_campaign_type_text_xpath = "//option[@value='Text']"
    textarea_primary_text_xpath = "//textarea[@id='p-text']"
    input_website_xpath = "//input[@id='web-url']"
    button_schedule_xpath = "//button[@id='item-add-schedule-btn']"
    td_start_date_xpath = "//*[@id='campaignModal']/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[2]"
    td_end_date_xpath = "//*[@id='campaignModal']/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[4]"
    option_start_hour_xpath = "//select[@class='hourselect']//option[@value='7'][normalize-space()='7']"
    option_start_minute_xpath = "//*[@id='campaignModal']/div[2]/div[1]/div[1]/div/div/select[2]/option[31]"
    option_start_am_xpath = "(//option[@value='AM'][normalize-space()='AM'])[1]"
    option_end_hour_xpath = "(//option[@value='10'][normalize-space()='10'])[3]"
    option_end_minute_xpath = "//*[@id='campaignModal']/div[2]/div[2]/div[1]/div/div/select[2]/option[51]"
    option_end_pm_xpath = "(//option[@value='PM'][normalize-space()='PM'])[2]"
    button_apply_xpath = "//button[normalize-space()='Apply']"
    button_publish_xpath = "//button[normalize-space()='Publish now']"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[2]"
    button_delete_xpath = ("//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[1]/play-pointz-campaigns[1]"
                           "/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[10]/button[2]")
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    input_search_campaign_xpath = "//input[@placeholder='Search campaign']"
    option_active_status_all_xpath = "(//option[contains(text(),'All')])[1]"
    option_active_status_active_xpath = "//option[@value='true']"
    option_active_status_inactive_xpath = "//option[@value='false']"
    option_sponsor_all_xpath = "(//option[contains(text(),'All')])[2]"
    option_sponsor_bairaha_xpath = "//option[@value='Bairaha']"
    option_sponsor_beverly_hills_polo_club_xpath = "//option[@value='Beverly Hills Polo Club']"
    option_sponsor_fadna_shape_up_tea_xpath = "//option[@value='Fadna Shape-Up Tea']"
    option_sponsor_stesafe_xpath = "//option[@value='Stesafe']"
    option_sponsor_fadna_tummy_tea_xpath = "//option[@value='Fadna Tummy Tea']"
    button_upload_image_xpath = "//button[normalize-space()='+Upload Media']"
    button_choose_image_xpath = "//button[normalize-space()='Choose new image']"
    input_start_date_xpath = "//input[@placeholder='Start Date']"
    input_end_date_xpath = "//input[@placeholder='End Date']"
    button_search_xpath = "(//button[normalize-space()='Search'])[1]"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    button_add_xpath = "//button[normalize-space()='Add']"
    button_export_xpath = "//button[normalize-space()='Export']"
    button_advanced_filter_xpath = "//button[normalize-space()='Advanced Filters']"
    image_path = "C:\\Users\\Ishadi\\Documents\\GitHub\\playpointz-test-automation\\Images\\test_image_campaign.jpg"
