class ComplainsLocators:
    hyperlink_complains_xpath = "//a[normalize-space()='Complains']"
    hyperlink_view_profile_xpath = "(//a[@title='View profile'][normalize-space()='hydenTest'])[1]"
    button_complain_xpath = "(//button[@title='Take action'])[1]"
    option_delete_post_xpath = "//option[@value='delete']"
    option_ban_user_xpath = "//option[@value='banned']"
    option_ignore_xpath = "//option[@value='ignore']"
    button_take_action_xpath = "//button[normalize-space()='Take action']"
    button_cancel_xpath = "//div[@class='inline-flex']//button[@type='button'][normalize-space()='Cancel']"
    button_delete_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/div/play-pointz-user-reporting/div" \
                          "/div[2]/div[2]/table/tbody/tr[1]/td[5]/button[2]"
    button_delete_cancel_xpath = "(//button[@type='button'][normalize-space()='Cancel'])[3]"
    input_search_reporter_xpath = "//input[@placeholder='Search reporter']"
    option_status_all_xpath = "//option[normalize-space()='All']"
    option_status_not_resolved_xpath = "//option[@value='false']"
    option_status_resolved_xpath = "//option[@value='true']"
    input_date_from_xpath = "//input[@placeholder='Start Date']"
    input_date_to_xpath = "//input[@placeholder='End Date']"
    button_search_xpath = "(//button[@type='submit'])[2]"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    button_ignore_xpath = "(//button[@title='Ignore'])[1]"
    button_accept_ignore_xpath = "//button[normalize-space()='Ignore']"
    button_advanced_filter_xpath = "//button[normalize-space()='Advanced Filters']"
