class GameLocators:
    hyperlink_game_xpath = "//a[normalize-space()='Games']"
    hyperlink_missing_character_xpath = "(//a[@class='nav-link btn-enter'])[1]"
    hyperlink_word_correction_xpath = "(//a[@class='nav-link btn-enter'])[2]"
    button_create_game_xpath = "//button[normalize-space()='Create Game']"
    input_word_xpath = "//input[@id='word']"
    button_shuffle_xpath = "//button[@class='btn btn-shuffel']"
    input_plus_pointz_xpath = "//input[@id='quiz-points']"
    input_minus_pointz_xpath = "//input[@id='quiz-minus']"
    option_easy_xpath = "//*[@id='game_level']/option[1]"
    input_answer1_xpath = "//input[@id='question_0']"
    input_answer2_xpath = "//input[@id='question_1']"
    input_answer3_xpath = "//input[@id='question_2']"
    input_answer4_xpath = "//input[@id='question_3']"
    option_status_xpath = "(//option[@value='true'][normalize-space()='Active'])[1]"
    button_save_xpath = "//button[normalize-space()='Save']"
    button_cancel_xpath = "(//button[@type='button'][normalize-space()='Cancel'])[2]"
    input_search_xpath = "//input[@placeholder='Search word']"
    button_search_xpath = "//button[@class='btn btn-search-sub']"
    select_difficulty_xpath = "//select[@id='difficulty']"
    option_difficulty_Default_xpath = "//option[normalize-space()='Default']"
    option_difficulty_Easy_xpath = "//option[@value='Easy']"
    option_difficulty_Hard_xpath = "//option[@value='Hard']"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2'])[1]"
    table_row1_xpath = "(//tr)[4]"
    table_row2_xpath = "(//tr)[8]"
    table_deleteRow_xpath = "(//tr)[2]"
    hyperlink_pagination_xpath = "//a[normalize-space()='3']"
    button_edit_game1_xpath = "(//button[@data-bs-toggle='modal'])[3]"
    button_edit_game2_xpath = "(//button[@data-bs-toggle='modal'])[3]"
    button_delete_xpath = "(//button[@data-bs-toggle='modal'])[4]"
    option_status_inactive_xpath = "//*[@id='status']/option[2]"
    button_deleteAccept_xpath = "//button[normalize-space()='Delete']"
    button_settings_xpath = "(//button[@class='btn me-2'])[1]"
    input_scheduleMinutes_xpath = "//input[@name='schedule_minutes']"
    option_activeStatus_xpath = "//*[@id='is_active']/option[1]"
    button_update_xpath = "//button[normalize-space()='Update']"
    button_add_answers_xpath = "//button[normalize-space()='Add answer']"
    input_answer_2_xpath = "(//input[@id='question_1'])[1]"
    button_edit_answeredGame_xpath = "(//button[@data-bs-toggle='modal'])[15]"
    button_close_xpath = "//button[@aria-label='Close']"
