class ItemsLocators:
    button_items_xpath = "//button[normalize-space()='Items']"
    hyperlink_items_xpath = "//a[normalize-space()='Items']"
    hyperlink_categories_xpath = "//*[@id='items-accord']/div/a[3]"
    hyperlink_scheduler_xpath = "//*[@id='items-accord']/div/a[2]"
    button_add_items_xpath = "//button[normalize-space()='Add item']"
    input_item_name_xpath = "//input[@id='item-name']"
    option_category_xpath = "//option[@value='0d3fa8ce-169f-44f8-ba47-90a88468eee9']"
    paragraph_description_xpath = "//div[@class='ql-editor ql-blank']//p"
    option_active_status_xpath = "//select[@id='active']//option[@value='true'][normalize-space()='Active']"
    input_stock_xpath = "//input[@id='stock']"
    input_pointz_xpath = "//input[@id='pointz']"
    button_save_xpath = "//button[normalize-space()='Save']"
    hyperlink_page_xpath = "//a[normalize-space()='2']"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[2]"
    button_delete_xpath = "(//button[@class='btn ms-0 me-0'])[1]"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    button_delete_item_exist_event_xpath = "(//button[@data-bs-toggle='modal'])[3]"
    input_search_item_xpath = "//input[@placeholder='Search item']"
    option_electronic_category_xpath = "//option[@value='Electronic']"
    option_beauty_category_xpath = "//option[@value='Beauty']"
    option_toys_category_xpath = "//option[@value='Toys']"
    option_game_category_xpath = "//option[@value='Game']"
    option_food_drink_category_xpath = "//option[@value='Food & Drink']"
    option_entertainment_category_xpath = "//option[@value='Entertainment']"
    option_gadget_category_xpath = "//option[@value='Gadget']"
    option_health_category_xpath = "//option[@value='Health']"
    option_special_days_xpath = "//option[@value='Special Days']"
    option_travel_xpath = "//option[@value='Travel']"
    option_fashion_xpath = "//option[@value='Fashion']"
    option_status_all_xpath = "(//option[contains(text(),'All')])[2]"
    option_status_end_xpath = "//option[@value='End']"
    option_status_ongoing_xpath = "//option[@value='Ongoing']"
    option_status_pending_xpath = "//option[@value='Pending']"
    option_active_status_all_xpath = "(//option[contains(text(),'All')])[3]"
    option_active_status_active_xpath = "(//option[@value='true'][normalize-space()='Active'])[2]"
    option_active_status_inactive_xpath = "(//option[@value='false'][normalize-space()='Inactive'])[2]"
    button_search_xpath = "(//button[@type='submit'])[3]"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    button_create_category_xpath = "//button[normalize-space()='Create category']"
    input_category_name_xpath = "//input[@id='cat-name']"
    input_search_category_xpath = "//input[@placeholder='Search category']"
    button_search_category_xpath = "//i[@class='fas fa-search']"
    button_new_scheduler_xpath = "//button[normalize-space()='New schedule']"
    input_name_xpath = "//input[@id='item']"
    input_quantity_xpath = "//input[@id='qty']"
    tableData_start_date_waiting_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[2]/table/tbody/tr[2]/td[3]"
    tableData_end_date_waiting_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[2]/table/tbody/tr[2]/td[5]"
    option_start_waiting_hour_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[1]/div/div/select[1]/option[8]"
    option_start_waiting_minute_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[1]/div/div/select[2]/option[31]"
    option_end_waiting_hour_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[1]/div/div/select[1]/option[8]"
    option_end_waiting_minute_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[1]/div/div/select[2]/option[31]"
    button_apply_xpath = "//*[@id='scheduleModal']/div[3]/div[3]/div/button[1]"
    option_active_date_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[3]"
    option_active_hour_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[1]/div/div/select[1]/option[10]"
    option_active_minute_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[1]/div/div/select[2]/option[31]"
    option_active_pm_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[1]/div/div/select[3]/option[2]"
    span_item_name_xpath = "(//button[@id='ngb-typeahead-0-0'])[1]"
    span_item_name2_xpath = "(//button[@id='ngb-typeahead-1-0'])[1]"
    span_item_name3_xpath = "//*[@id='ngb-typeahead-2-0']"
    input_schedule_time_xpath = "//input[@id='waitingDate']"
    tabledata_start_time_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[2]/table/tbody/tr[2]/td[5]"
    tabledata_end_time_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[2]/table/tbody/tr[2]/td[4]"
    option_start_hour_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[1]/div/div/select[1]/option[6]"
    option_end_hour_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[1]/div/div/select[1]/option[10]"
    option_start_minute_xpath = "//*[@id='scheduleModal']/div[3]/div[1]/div[1]/div/div/select[2]/option[31]"
    option_end_minute_xpath = "//*[@id='scheduleModal']/div[3]/div[2]/div[1]/div/div/select[2]/option[31]"
    input_active_end_time_xpath = "//input[@id='singledate']"
    tabledata_active_end_date_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[2]/table/tbody/tr[5]/td[7]"
    option_active_end_hour_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[1]/div/div/select[1]/option[10]"
    option_active_end_minute_xpath = "//*[@id='scheduleModal']/div[2]/div[1]/div[1]/div/div/select[2]/option[31]"
    button_apply1_xpath = "(//button[@type='button'][normalize-space()='Apply'])[1]"
    div_edit_schedule_date_xpath = "(//div[@class='fc-daygrid-day-top'])[4]"
    button_edit_schedule_xpath = "//*[@id='scheduleModal']/div[1]/div/form/div[3]/table/tbody/tr[1]/td[4]/button[1]"
    button_left_arrow_xpath = "//div[@class='calendar-handler']//button[@title='Previous month']"
    div_delete_schedule_date_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                                     "1]/play-pointz-item-schedule[1]/div[1]/div[3]/div[2]/div[1]/table[1]" \
                                     "/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]" \
                                     "/div[1]/div[1]"
    button_delete_schedule_xpath = "(//button[@type='button'])[18]"
    hyperlink_page2_xpath = "//a[normalize-space()='2']"
    button_edit_categories_xpath = "//td[@class='align-middle']//button[@class='btn']"
    button_upload_image_xpath = "//button[normalize-space()='Choose new image']"
    table_item_table_xpath = "//table[@class='table align-middle']"
    button_advanced_search_xpath = "//button[normalize-space()='Advanced Filters']"
    button_close_xpath = "//button[@aria-label='Close']"
    image_item_path = "C:\\Users\\Ishadi\\Pictures\\playpointz_images\\Test_Image_Item.png"
    image_category_path = "C:\\Users\\Ishadi\\Pictures\\playpointz_images\\test_category_icon.png"
