class PlayerSupportLocators:
    hyperlink_player_support_xpath = "//a[normalize-space()='player Support']"
    input_search_by_name_xpath = "//input[@placeholder='Search player Name']"
    option_access_all_xpath = "//option[normalize-space()='All']"
    option_access_action_taken_xpath = "//option[normalize-space()='Action taken']"
    option_access_action_required_xpath = "//option[normalize-space()='Action required']"
    input_start_date_xpath = "//input[@placeholder='Start Date']"
    input_end_date_xpath = "//input[@placeholder='End Date']"
    button_search_xpath = "(//button[@type='submit'])[2]"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    button_view_xpath = "(//button[@title='View'])[8]"
    button_page_xpath = "(//li[@class='page-item'])[6]"
    hyperlink_page_11_xpath = "(//a[normalize-space()='11'])[1]"
    select_status_xpath = "//select[@name='status']"
    option_resolved_xpath = "//option[normalize-space()='Resolved']"
    option_not_resolved_xpath = "//option[normalize-space()='Not Resolved']"
    button_take_action_xpath = "//button[normalize-space()='Take action']"
    button_close_xpath = "//button[normalize-space()='Close']"
    hyperlink_view_profile_xpath = "(//a[@title='View profile'][normalize-space()='Hyden Taylor'])[1]"
    input_subject_xpath = "//input[@placeholder='Subject']"
    paragraph_comment_xpath = "//div[@class='ql-editor ql-blank']//p"
    button_choose_image_xpath = "//button[normalize-space()='Choose new image']"
    button_send_xpath = "//button[normalize-space()='Send']"
    button_reset_xpath = "//button[normalize-space()='Reset']"
    button_mark_as_resolved_xpath = "(//button[@class='btn'][normalize-space()='Mark as Resolve'])[1]"
    button_accept_xpath = "(//button[@type='button'][normalize-space()='Mark as Resolve'])[1]"
    select_type_xpath = "//select[@id='type']"
    option_image_xpath = "//option[@value='Image']"
    button_advanced_filter_xpath = "(//button[normalize-space()='Advanced Filters'])[1]"
    image_path = "C:\\Users\\Ishadi\\Documents\\GitHub\\playpointz-test-automation\\Images\\test_image_support.jpg"
