class PlayerManagementLocators:
    hyperlink_player_management_xpath = "//a[normalize-space()='player Management']"
    input_search_username_xpath = "//input[@name='search']"
    input_search_brand_page_name_xpath = "//*[@id='brand-tab-pane']/play-pointz-player-list-template/div[1]/div[" \
                                         "1]/div/form/input"
    input_search_point_from_xpath = "//input[@placeholder='Points from']"
    input_search_point_to_xpath = "//input[@placeholder='Points to']"
    input_search_reg_date_from_xpath = "//input[@title='Reg date from']"
    input_search_reg_date_from_brand_pages_xpath = "(//input[@placeholder='Start Date'])[3]"
    input_search_reg_date_to_xpath = "//input[@title='Reg date to']"
    input_search_reg_date_to_brand_pages_xpath = "//*[@id='brand-tab-pane']/play-pointz-player-list-template/div[" \
                                                 "1]/div[" \
                                                 "1]/div/form/div/div/div[2]/div/div[2]/input"
    option_pointz_default = "//option[normalize-space()='Default']"
    option_pointz_ascending = "//option[@value='ASC']"
    option_pointz_descending = "//option[@value='DESC']"
    option_status_all = "(//option[contains(text(),'All')])[1]"
    option_status_all_brand_pages_xpath = "(//option[contains(text(),'All')])[6]"
    option_status_blocked = "(//option[normalize-space()='Blocked'])[1]"
    option_status_blocked_brand_pages_xpath = "(//option[@value='true'][normalize-space()='Blocked'])[2]"
    option_status_active = "//option[@value='false'][normalize-space()='Active']"
    option_status_active_brand_pages_xpath = "(//option[@value='false'][normalize-space()='Active'])[2]"
    option_verify_status_all = "(//option[contains(text(),'All')])[1]"
    option_verify_status_all_brand_pages_xpath = "(//option[contains(text(),'All')])[5]"
    option_verify_status_verified = "//option[normalize-space()='Verified']"
    option_verify_status_verified_brand_pages_xpath = "(//option[@value='true'][normalize-space()='Verified'])[2]"
    option_verify_status_not_verified = "//option[normalize-space()='Not Verified']"
    option_verify_status_not_verified_brand_pages_xpath = "(//option[@value='false'][normalize-space()='Not " \
                                                          "Verified'])[2]"
    option_referral_status_all = "(//option[contains(text(),'All')])[3]"
    option_referral_status_all_brand_pages_xpath = "(//option[contains(text(),'All')])[7]"
    option_referral_status_by_referral = "//option[normalize-space()='By Referral']"
    option_referral_status_by_referral_brand_pages_xpath = "(//option[@value='true'][normalize-space()='By " \
                                                           "Referral'])[2]"
    option_referral_status_direct = "//option[normalize-space()='Direct']"
    option_referral_status_direct_brand_pages_xpath = "(//option[@value='false'][normalize-space()='Direct'])[2]"
    option_active_status_all = "(//option[contains(text(),'All')])[4]"
    option_active_status_all_brand_pages_xpath = "(//option[contains(text(),'All')])[8]"
    option_active_status_active = "(//option[@value='true'][normalize-space()='Active'])[1]"
    option_active_status_active_brand_pages_xpath = "(//option[@value='true'][normalize-space()='Active'])[3]"
    option_active_status_de_active = "(//option[normalize-space()='Deactive'])[1]"
    option_active_status_de_active_brand_pages_xpath = "(//option[@value='false'][normalize-space()='Deactive'])[2]"
    button_search_xpath = "//button[normalize-space()='Search']"
    button_search_brand_page_xpath = "(//button[@type='submit'][normalize-space()='Search'])[2]"
    button_advanced_filter_xpath = "//button[normalize-space()='Advanced Filters']"
    button_advanced_filter_brand_pages_xpath = "(//button[@type='button'][normalize-space()='Advanced Filters'])[2]"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    button_refresh_brand_pages_xpath = "(//button[@type='button'])[17]"
    hyperlink_view_profile_xpath = "(//a[@title='View profile'])[5]"
    hyperlink_view_profile_brand_pages_xpath = "(//a[@title='View profile'])[11]"
    button_view_profile_see_more_xpath = "(//button[@class='btn see-more-btn'][normalize-space()='See more'])[1]"
    button_view_profile_see_more_again_xpath = "(//button[@class='btn see-more-btn'][normalize-space()='See more'])[2]"
    button_delete_post_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                               "1]/play-pointz-player-posts[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[" \
                               "5]/button[1]"
    button_accept_delete_post_xpath = "//button[normalize-space()='Delete']"
    button_cancel_xpath = "(//button[@type='button'][normalize-space()='Cancel'])[2]"
    button_edit_xpath = "//button[@title='Edit']"
    option_purchase_block_xpath = "(//option[@value='true'][normalize-space()='Block'])[2]"
    option_purchase_unblock_xpath = "(//option[@value='false'][normalize-space()='Unblock'])[2]"
    input_purchase_block_start_date_xpath = "(//input[@title='Purchase Block Start Date'])[1]"
    input_purchase_block_end_date_xpath = "(//input[@placeholder='End Date'])[1]"
    input_block_end_date_xpath = "//input[@title='Block End Date']"
    button_take_action_xpath = "//button[normalize-space()='Take action']"
    button_edit_cancel_xpath = "(//button[@type='button'][normalize-space()='Cancel'])[2]"
    button_edit_block_status_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                                     "1]/play-pointz-player-list[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[" \
                                     "6]/button[1]"
    option_block_xpath = "//*[@id='block-status']/option[1]"
    option_unblock_xpath = "//*[@id='block-status']/option[2]"
    select_status_block_xpath = "//div[@class='modal-content']//div[1]//select[1]"
    button_export_xpath = "//button[normalize-space()='Export']"
    list_page_one_xpath = "/html[1]/body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                          "1]/play-pointz-player-list[1]/div[1]/div[2]/div[3]/nav[1]/ul[1]/li[2]"
    list_page_7_xpath = "//*[@id='player-tab-pane']/play-pointz-player-list-template/div[1]/div[3]/nav/ul/li[8]"
    button_brand_pages_xpath = "//button[@id='brand-tab']"
    button_export_brand_pages_xpath = "(//button[@class='btn btn-search-sub ms-auto d-flex align-items-center " \
                                      "export_btn'][normalize-space()='Export'])[2]"
    button_edit_brand_pages_xpath = "(//button[@title='Edit'])[11]"
    option_block_status_brand_pages_block_xpath = "(//option[@value='true'][normalize-space()='Block'])[3]"
    option_block_status_brand_pages_unblock_xpath = "(//option[@value='false'][normalize-space()='Unblock'])[3]"
    option_verify_status_brand_pages_verified_xpath = "(//option[@value='true'][normalize-space()='Verified'])[3]"
    option_verify_status_brand_pages_not_verified_xpath = "(//option[@value='false'][normalize-space()='Not " \
                                                          "Verified'])[3]"
    select_block_status_brand_page_xpath = "(//select[@id='block-status'])[4]"
    input_block_end_date_brand_page_xpath = "//input[@placeholder='End Date']"
    select_verify_status_brand_pages_xpath = "(//select[@id='block-status'])[5]"
    select_active_status_brand_pages_xpath = "(//select[@id='block-status'])[6]"
    option_active_status_brand_pages_active_xpath = "(//option[@value='true'][normalize-space()='Active'])[4]"
    option_active_status_brand_pages_de_active_xpath = "(//option[@value='false'][normalize-space()='De Activate'])[2]"
    button_take_action_brand_pages_xpath = "(//button[@type='submit'][normalize-space()='Take action'])[2]"
