class PushNotificationsLocators:
    hyperlink_push_notifications_xpath = "//a[normalize-space()='Push Notifications']"
    button_create_notifications_xpath = "//button[normalize-space()='Create Notification']"
    input_title_xpath = "//input[@id='title']"
    textarea_message_xpath = "//textarea[@id='msg']"
    input_date_time_xpath = "//input[@id='schedule']"
    button_send_xpath = "//button[normalize-space()='Send']"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[2]"
    button_delete_xpath = "(//button[@data-bs-toggle='modal'])[3]"
    button_cancel_xpath = "(//button[@type='button'][normalize-space()='Cancel'])[3]"
    button_accept_delete_xpath = "(//button[normalize-space()='Delete'])[1]"
    input_search_xpath = "//input[@placeholder='Search title']"
    button_search_xpath = "(//button[@class='btn btn-search-sub ms-2'])[1]"
    button_refresh_xpath = "(//button[@type='button'])[10]"
    button_resend_xpath = "(//button[@type='button'])[10]"
    button_accept_resend_xpath = "//button[normalize-space()='Resend']"
