class QuizPageLocators:
    button_quizzes_xpath = "//*[@id='headingOne']/button"
    hyperlink_quizzes_xpath = "//a[normalize-space()='Quizzes']"
    hyperlink_scheduler_xpath = "//a[normalize-space()='Scheduler']"
    hyperlink_categories_xpath = "//a[normalize-space()='Categories']"
    button_create_quiz_xpath = "//button[normalize-space()='Create quiz']"
    input_quiz_name_xpath = "//input[@id='quiz-name']"
    input_plus_points_xpath = "//input[@name='points']"
    input_minus_points_xpath = "//input[@name='minus-points']"
    input_scheduled_quiz_xpath = "//input[@id='schedule']"
    input_sponsor_xpath = "//input[@id='is_sponsored']"
    select_quiz_type_xpath = "//select[@id='type']"
    option_image_xpath = "//option[@value='Image']"
    option_video_xpath = "//option[@value='Video']"
    option_youtube_video_xpath = "//option[@value='Youtube']"
    input_youtube_video_xpath = "//input[@name='youtube']"
    button_image_xpath = "//button[normalize-space()='Choose new image']"
    textarea_description_xpath = "//textarea[@id='desc']"
    input_quiz_category_xpath = "//input[@id='quiz']"
    button_computer_science_xpath = "(//button[@id='ngb-typeahead-0-0'])[1]"
    select_quiz_level_xpath = "//select[@id='quiz_level']"
    option_easy_xpath = "//*[@id='quiz_level']/option[1]"
    button_add_answer_xpath = "//button[normalize-space()='Add answer']"
    input_answer_1_xpath = "//input[@id='question_0']"
    input_answer_2_xpath = "//input[@id='question_1']"
    input_answer_3_xpath = "//input[@id='question_2']"
    input_answer_4_xpath = "//input[@id='question_3']"
    option_correct_answer_xpath = "//select[@id='state_0']//option[@value='true'][normalize-space()='Correct']"
    option_status_xpath = "//option[normalize-space()='Active']"
    option_approve_xpath = "(//option[@value='true'][normalize-space()='Approved'])[2]"
    button_save_xpath = "//button[normalize-space()='Save']"
    table_row_edit_xpath = "(//tr)[10]"
    button_edit_xpath = "(//button[@class='btn ms-0 me-3'])[1]"
    hyperlink_page_xpath = "//a[normalize-space()='12']"
    button_update_xpath = "//button[normalize-space()='Save']"
    button_delete_xpath = "//button[@data-bs-target='#delete-quiz-modal']"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    input_search_quiz_xpath = "//input[@placeholder='Search quiz']"
    button_search_xpath = "//button[@class='btn btn-search-sub']"
    option_difficulty_default_xpath = "//option[normalize-space()='Default']"
    option_difficulty_easy_xpath = "//option[@value='Easy']"
    option_difficulty_hard_xpath = "//option[@value='Hard']"
    button_refresh_xpath = "(//button[@class='btn btn-search-sub ms-2 rounded_'])[1]"
    input_search_category_xpath = "//input[@placeholder='Search category']"
    button_upload_image_xpath = "//button[normalize-space()='Choose new image']"
    input_upload_video_xpath = "//input[@name='video']"
    button_normal_quiz_xpath = "//button[contains(text(),'Normal Quizzes')]"
    hyperlink_quiz_pool_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/play-pointz-side-bar/div/ul/li[" \
                                "2]/div/div/div/div/a[1]"
    hyperlink_quiz_scheduler_xpath = "(//a[@class='btn w-100 text-left'][normalize-space()='Quiz Scheduler'])[1]"
    button_single_quiz_xpath = "//button[normalize-space()='Single Quizzes']"
    hyperlink_quiz_pool_2_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/play-pointz-side-bar/div/ul/li["\
                                  "3]/div/div/div/div/a[1]"
    image_path = "C:\\Users\\Ishadi\\Documents\\GitHub\\playpointz-test-automation\\Images\\test_image_quiz.jpg"

