class SchedulePageLocators:
    button_quizzes_xpath = "//*[@id='headingOne']/button"
    hyperlink_schedule_xpath = "//*[@id='quizess-accord']/div/a[2]"
    div_day_grid_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/div/play-pointz-quiz-schedule/div[" \
                         "3]/div[2]/div/table/tbody/tr/td/div/div/div/table/tbody/tr[3]/td[4]/div"
    button_edit_schedule_xpath = "//tbody//tr//button[1]"
    select_quiz_level_xpath = "(//select[@id='quiz-level'])[1]"
    option_hard_xpath = "//*[@id='quiz-level']/option[1]"
    input_quiz_category_xpath = "//input[@id='quiz']"
    input_schedule_time_xpath = "//*[@id='singledateQ']"
    table_data_start_time_xpath = "//*[@id='scheduleModalQ']/div[2]/div[1]/div[2]/table/tbody/tr[3]/td[1]"
    table_data_end_time_xpath = "//*[@id='scheduleModalQ']/div[2]/div[2]/div[2]/table/tbody/tr[3]/td[6]"
    select_start_hour_xpath = "//select[@class='hourselect']"
    select_end_hour_xpath = "//select[@class='hourselect disabled']"
    option_start_hour_xpath = "//select[@class='hourselect']//option[@value='9'][normalize-space()='9']"
    select_start_minute_xpath = "//select[@class='minuteselect']"
    select_end_minute_xpath = "//select[@class='minuteselect disabled']"
    option_start_minute_xpath = "//select[@class='minuteselect']//option[@value='30'][normalize-space()='30']"
    option_end_hour_xpath = "//*[@id='scheduleModalQ']/div[2]/div[2]/div[1]/div/div/select[1]/option[8]"
    button_save_xpath = "//button[normalize-space()='Save']"
    button_clear_xpath = "//button[normalize-space()='Clear']"
    button_close_xpath = "//button[normalize-space()='Close']"
    arrow_left_xpath = "//div[@class='calendar-handler']//span[@class='fc-icon fc-icon-chevron-left']"
    div_day_grid_delete_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                                "1]/play-pointz-quiz-schedule[1]/div[3]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[" \
                                "1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[4]/div[1]/div[1]"
    button_apply_xpath = "//button[normalize-space()='Apply']"
    button_delete_xpath = "(//button[@type='button'])[18]"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    button_reject_delete_xpath = "//div[@id='delete-quiz-modal']//button[@type='button'][normalize-space()='Cancel']"
    button_new_scheduler_xpath = "//button[normalize-space()='New schedule']"
    span_quiz_category_xpath = "//*[@id='ngb-typeahead-0-0']/span"
    option_quiz_level_hard_xpath = "//option[@value='f4f06281-2924-4d58-8341-bdce22330dc1']"
    div_edit_xpath = ("/html/body/play-pointz-root/play-pointz-layout/main/div/play-pointz-quiz-schedule"
                      "/div[3]/div[2]/div/table/tbody/tr/td/div/div/div/table/tbody/tr[3]/td[5]/div/div[1]")
    hyperlink_normal_quiz_scheduler_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/play-pointz-side-bar" \
                                            "/div/ul/li[2]/div/div/div/div/a[2]"
    hyperlink_single_quiz_scheduler_xpath = "/html/body/play-pointz-root/play-pointz-layout/main/play-pointz-side-bar" \
                                            "/div/ul/li[3]/div/div/div/div/a[2]"
    input_quiz_name_xpath = "//input[@id='quiz']"
    span_quiz_name_xpath = "(//strong[normalize-space()='Quiz'])[1]"
    input_single_quiz_xpath = "//input[@id='singledateSQ']"
    table_heading_previous_xpath = "//th[@class='prev available']"
    table_heading_next_xpath = "//th[@class='next available']"
    table_data_single_quiz_start_date_xpath = "//*[@id='scheduleModalQ']/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[3]"
    table_data_single_quiz_end_date_xpath = "//*[@id='scheduleModalQ']/div[2]/div[2]/div[2]/table/tbody/tr[4]/td[2]"
    option_single_quiz_start_hour_xpath = "//select[@class='hourselect']//option[@value='10'][normalize-space()='10']"
    option_single_quiz_start_minute_xpath = "(//option[@value='30'][normalize-space()='30'])[1]"
    option_typography_pm_xpath = "(//option[@value='PM'][normalize-space()='PM'])[1]"
    option_single_quiz_end_hour_xpath = "(//option[@value='4'][normalize-space()='4'])[2]"
    option_single_quiz_end_minute_xpath = "(//option[@value='35'][normalize-space()='35'])[2]"
    option_typography_am_xpath = "(//option[@value='AM'][normalize-space()='AM'])[2]"
    option_quiz_level_easy_xpath = "//*[@id='quiz-level']/option[2]"
