class SettingsLocators:
    button_settings_xpath = "//button[normalize-space()='Settings']"
    hyperlink_general_xpath = "(//a[normalize-space()='General'])[1]"
    hyperlink_email_domain_xpath = "//a[normalize-space()='Email Domains']"
    button_edit1_xpath = "(//button[@data-bs-toggle='modal'])[1]"
    button_edit2_xpath = "(//button[@data-bs-toggle='modal'])[2]"
    input_quiz_lower_bound_xpath = "(//input[@id='lower-bound'])[1]"
    input_quiz_upper_bound_xpath = "(//input[@id='upper-bound'])[1]"
    button_save_xpath = "(//button[@type='submit'][normalize-space()='Save'])[1]"
    tablerow_row1_xpath = "(//tr)[2]"
    tablerow_row2_xpath = "(//tr)[3]"
    button_create_email_xpath = "//button[normalize-space()='Create email']"
    input_allowed_email_xpath = "//input[@id='email']"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[6]"
    button_delete_xpath = "(//button[@data-bs-toggle='modal'])[5]"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    input_search_xpath = "//input[@placeholder='Search email']"
    button_search_xpath = "(//button[@class='btn btn-search-sub ms-2'])[1]"
    button_refresh_xpath = "(//button[@type='button'])[10]"
    input_quiz_limit_xpath = "//input[@id='quiz-limit']"
    input_daily_pointz_easy_xpath = "//input[@id='daily_easy']"
    input_daily_pointz_hard_xpath = "//input[@id='daily_hard']"
    input_minus_pointz_easy_xpath = "//input[@id='minus_easy']"
    input_minus_pointz_hard_xpath = "//input[@id='minus_hard']"
    heading_settings_xpath = "//h3[normalize-space()='Settings']"
    input_join_pointz_xpath = "//input[@id='join_points']"
    input_referral_pointz_xpath = "//input[@id='referral_points']"
    input_recent_winner_count_xpath = "//input[@id='recent_winners_count']"
    input_schedule_expire_xpath = "//input[@id='schedule_expire_days']"
    input_logo_xpath = "//input[@id='logo']"
    span_preview_logo_xpath = "//span[@id='logo-addon']"
    button_close_xpath = "(//button[@aria-label='Close'])[3]"
    button_settings_save_xpath = "(//button[@class='btn form-submit-btn mt-3'])[1]"
    heading_app_logo_xpath = "//h3[normalize-space()='App Logo']"
