class StoreBannersLocators:
    hyperlink_store_banners_xpath = "//a[normalize-space()='Store Banners']"
    button_create_store_banners_xpath = "//button[normalize-space()='Create banner']"
    input_redirect_url_xpath = "//input[@id='cat-name']"
    button_image_xpath = "//button[normalize-space()='Choose new image']"
    textarea_description_xpath = "//textarea[@id='desc']"
    button_save_xpath = "//button[normalize-space()='Save']"
    button_delete_xpath = "(//button[@data-bs-toggle='modal'])[3]"
    button_accept_delete_xpath = "//button[normalize-space()='Delete']"
    button_edit_xpath = "(//button[@data-bs-toggle='modal'])[2]"
    select_sequence_xpath = "(//select[@id='_index0'])[1]"
    option_value_six_xpath = "(//option[@value='6'][normalize-space()='6'])[1]"
    image_path = "C:\\Users\\Ishadi\\Documents\\GitHub\\playpointz-test-automation\\Images\\test_image_banner.jpg"
