class UserManagementLocators:
    button_users_xpath = "//button[normalize-space()='users']"
    hyperlink_user_role_xpath = "//a[normalize-space()='User Role']"
    hyperlink_user_management_xpath = "//a[normalize-space()='User Management']"
    button_add_member_xpath = "//button[normalize-space()='Add member']"
    input_username_xpath = "//input[@id='username']"
    button_generate_password_xpath = "//button[normalize-space()='Generate Password']"
    input_email_xpath = "//input[@id='email']"
    input_first_name_xpath = "//input[@id='f-name']"
    input_last_name_xpath = "//input[@id='l-name']"
    option_role_xpath = "(//option[@value='86bcc265-4a7f-4865-8030-98d3dedce060'])[1]"
    option_status_active_xpath = "//option[@value='true']"
    option_status_inactive_xpath = "//option[@value='false']"
    button_save_xpath = "//button[normalize-space()='Save']"
    button_edit_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[1]/play-pointz-roles[1]/div[" \
                        "1]/div[2]/div[1]/table[1]/tbody[1]/tr[11]/td[2]/button[1]"
    button_edit_2_xpath = "(//button[@data-bs-toggle='modal'])[10]"
    input_search_xpath = "//input[@placeholder='Search member']"
    button_search_xpath = "(//button[normalize-space()='Search'])[1]"
    button_add_role_xpath = "//button[normalize-space()='Add user role']"
    input_role_name_xpath = "//input[@id='role-name']"
    input_permission_xpath = "//input[@aria-autocomplete='list']"
    button_edit_user_role_xpath = "//body[1]/play-pointz-root[1]/play-pointz-layout[1]/main[1]/div[" \
                                  "1]/play-pointz-roles[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/button[1]"
    span_user_reporting_xpath = "//span[normalize-space()='User Reportings']"
    span_permission_xpath = "//span[normalize-space()='Quizzes']"
    span_remove_permission_xpath = "//span[@class='ng-value-icon left']"
